version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGUSER: ${PGUSER:-postgres}
      PGDATABASE: ${PGDATABASE:-postgres}
      PGPASSWORD: ${PGPASSWORD:-password}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-5432}:5432
    restart: always

  app:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 0.0.0.0:8000:80
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

volumes:
  db_data:
